### ISSUE TITLE
‘uv_async_t’ does not name a type

### ISSUE THREAD

**Issue by haplo31** [kiriapurv/node-camera#1]
Hi,
It seems your code doesn't work with recents node versions.
I have the message : 
  CXX(target) Release/obj.target/camera/src/native/camera.o
../src/native/camera.cpp:25:1: error: ‘uv_async_t’ does not name a type

when I try to run npm install with node v0.12.1.

Do you know how I could install correctly ?

Thanks for your help.
John

**Comment by kiriapurv** [comment]
iojs branch has latest v8 support, try building it.

**Comment by haplo31** [comment]
It works, thanks a lot !
