### ISSUE TITLE
Addon only works for node v0.10?

### ISSUE THREAD

**Issue by jas0n1ee** [kiriapurv/node-camera#3]
I try to compile the code with node version 0.10, 0.12, 4.1.2, and only 0.10 works. Since node changes the addon api quite often, why node use NAN instead?

**Comment by kiriapurv** [comment]
I didn't know about nan when I wrote node-camera, and v8 changes affected as much as 3-4 lines of code, anyways its good idea to switch to nan for future development. For now you can use [iojs branch](https://github.com/kiriapurv/node-camera/tree/iojs) for 0.11 < node-version < 4.x, and I have pushed latest changes for 4.x in [node-4.x branch](https://github.com/kiriapurv/node-camera/tree/node-4.x)

**Comment by jas0n1ee** [comment]
👍👍👍
